#ifndef LANG_H
#define LANG_H

// Game UI Strings (English)
#define STR_TITLE               "  BARBEQUE CHICKEN ALERT NDS  "
#define STR_CHICKENS            " Chickens: %-18llu"
#define STR_CPS_REBIRTH         " CPS:%-5.1f|Rebirth:%-2d(%0.1fx)"
#define STR_TAB_UPG             "1:UPG "
#define STR_TAB_BANK            "2:BANK"
#define STR_TAB_REB             "3:REB "
#define STR_TAB_STAT            "4:STAT"

#define STR_UPG_0               "Main Popup Gain"
#define STR_UPG_0_INFO          "Gain: +%llu"
#define STR_UPG_1               "Auto Clicker"
#define STR_UPG_1_INFO          "Auto Popup Tap"
#define STR_UPG_2               "Chicken Breast"
#define STR_UPG_2_INFO          "Unlock Breast"
#define STR_UPG_3               "Hire Cook"
#define STR_UPG_3_INFO          "Count: %d"
#define STR_UPG_4               "Cook CPS Boost"
#define STR_UPG_4_INFO          "Lvl: %d/5"
#define STR_UPG_5               "Click Power"
#define STR_UPG_5_INFO          "Lvl: %d/10"
#define STR_UPG_6               "Popup Speed"
#define STR_UPG_6_INFO          "Lvl: %d"
#define STR_UPG_7               "Unlock Factory"
#define STR_UPG_7_INFO          "Unlock Factory"
#define STR_UPG_8               "Buy Factory"
#define STR_UPG_8_INFO          "Count: %d"
#define STR_UPG_9               "Factory CPS Boost"
#define STR_UPG_9_INFO          "Lvl: %d/5"
#define STR_UPG_10              "Unlock Bank"
#define STR_UPG_10_INFO         "Unlock Bank"
#define STR_UPG_11              "Bank Decay Delay"
#define STR_UPG_11_INFO         "Lvl: %d/5"
#define STR_UPG_12              "Rare Chance Boost"
#define STR_UPG_12_INFO         "Lvl: %d/3"

#define STR_LOCKED              "??? Locked"
#define STR_OWNED               "[OWNED]"
#define STR_COST_FMT            "Cost: %llu (%s)"

#define STR_BANK_TITLE          "     === CHICKEN BANK ===     "
#define STR_BANK_LOCKED_1       " Bank is currently locked!    "
#define STR_BANK_LOCKED_2       " Unlock in Upgrades tab for   "
#define STR_BANK_LOCKED_3       " 5,000 chickens.              "
#define STR_BANK_STORED         " Stored: %-20llu"
#define STR_BANK_RATE           " Rate:   %-8.1f CPS (%d%%)"
#define STR_BANK_CTRL_HEADER    " Controls:                    "
#define STR_BANK_CTRL_DEP       "  [\x1b[33;1mX\x1b[0m] Deposit 10%% Chickens      "
#define STR_BANK_CTRL_WD        "  [\x1b[33;1mY\x1b[0m] Withdraw 10%% Chickens     "

#define STR_REB_TITLE           "  === REBIRTH / PRESTIGE ===  "
#define STR_REB_COUNT           " Rebirths: %-18d"
#define STR_REB_MULTI           " Multiplier: %-16.1fx"
#define STR_REB_REQ             " Req Upgrade Lvl:%-2d(Cur:%d)"
#define STR_REB_GAIN            " Gained RC: %-17llu"
#define STR_REB_READY           " \x1b[32;1m>> PRESS [A] TO REBIRTH <<   \x1b[0m"
#define STR_REB_NOT_READY       " Reach Upgrade Lvl %d to Rebirth"

#define STR_STAT_TITLE          "   === STATISTICS & SAVE ===  "
#define STR_STAT_TAPS           " Manual Taps:    %-12llu"
#define STR_STAT_RARE           " Rare Popups:    %-12llu"
#define STR_STAT_COOK           " Cook Output:    %-12llu"
#define STR_STAT_FACTORY        " Factory Output: %-12llu"
#define STR_STAT_STATUS         " Status: \x1b[33;1m%-20s\x1b[0m"

#define STR_FOOTER_1            " [D-Pad] Move/Tab | [A] Buy   "
#define STR_FOOTER_2            " [X/Y] Bank Dep/Wd| [SEL] Save"

#endif // LANG_H
